version: '3.9'
services:
  app:
    image: docker-practice-api:latest-dev
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: ["/myapp"]
    ports:
      - "$API_PORT:3000" # auto from .env var
    pid: "host"
